backend/config/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as main_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
# from rest_framework_simplejwt.views import (
#     TokenObtainPairView,
#     TokenRefreshView,
# )

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.Home.as_view()),
    path('register/', main_views.RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('products/', main_views.ProductListAPIView.as_view()),
    path('api/', include('main.urls')),
    path('auth/', include('dj_rest_auth.urls')),
    path('auth/registration/', include('dj_rest_auth.registration.urls')),
    # path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/main/urls.py
# from rest_framework.routers import DefaultRouter

# from .views import (
#     UserViewSet,
#     ProductViewSet
# )

# router = DefaultRouter()

# router.register(r'users', UserViewSet)
# router.register(r'products', ProductViewSet)
# router.register(r'products/', ProductViewSet)

# urlpatterns = router.urls


from django.urls import path
from main.views import ProductListAPIView, ProductDetailAPIView

urlpatterns = [
    path('products/', ProductListAPIView.as_view(), name="list"),
    path('products/<int:id>/', ProductDetailAPIView.as_view(), name="detail"),

]

backend/main/models.py
from django.db import models
from versatileimagefield.fields import VersatileImageField
from django.utils.translation import gettext as _
from main.utils import TimeStampedModel


class Product(TimeStampedModel):
    title = models.CharField(_("Ürün ismi"), max_length=50)
    brief = models.CharField(_("Kısa bilgi"), max_length=250)
    description = models.CharField(_("Hakkında"), max_length=1000)
    image = VersatileImageField(
        'Fotograf',
        upload_to='product_images/'
    )

    def __str__(self):
        return self.title

backend/main/forms.py
from django import forms

from django.contrib.auth import get_user_model

User = get_user_model()


class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email',)

    def clean_email(self):
        email = self.cleaned_data.get("email")
        qs = User.objects.filter(email__iexact=email)
        if qs.exists():
            raise forms.ValidationError(
                "Cannot use this email. It's already registered")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        #user.password = "asdfasd"
        user.is_active = False

        if commit:
            user.save()
            # create a new user hash for activating email.
        return user

backend/main/views.py
from .serializers import (
    UserSerializer
)
from django.shortcuts import render
from main.models import Product
from django.views.generic import ListView
from main.forms import RegisterForm

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, DetailView, View
from rest_framework.generics import ListAPIView, RetrieveAPIView
from main.serializers import ProductSerializer
from rest_framework.viewsets import ModelViewSet
from main.pagination import ProductLimitOffsetPagination, ProductPagePagination


User = get_user_model()


class ProductListAPIView(ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    pagination_class = ProductPagePagination

    def filter_queryset(self, queryset):
        queryset = super(ProductListAPIView, self).filter_queryset(queryset)
        return queryset.order_by('-modified_at')


class ProductDetailAPIView(RetrieveAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    lookup_field = 'id'


class UserViewSet(ModelViewSet):

    queryset = User.objects.all()
    serializer_class = UserSerializer


# class ProductViewSet(ViewSet):

#     def list(self, request):
#         paginate_by = 20
#         queryset = Product.objects.all()
#         serializer = ProductSerializer(queryset)
#         return Response(serializer.data)

#     def retrieve(self, request, pk=None):
#         queryset = User.objects.all()
#         product = get_object_or_404(queryset, pk=pk)
#         serializer = ProductSerializer(product)
#         return Response(serializer.data)

#     def filter_queryset(self, queryset):
#         queryset = super(ProductViewSet, self).filter_queryset(queryset)
#         return queryset.order_by('-modified_at')


class RegisterView(SuccessMessageMixin, CreateView):
    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = '/'
    success_message = "Your account was created successfully. Please check your email."

    def dispatch(self, *args, **kwargs):
        # if self.request.user.is_authenticated():
        #     return redirect("/logout")
        return super(RegisterView, self).dispatch(*args, **kwargs)


class Home(ListView):
    queryset = Product.objects.all()
    template_name = "base.html"
    context_object_name = "products"
    paginate_by = 20

backend/main/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
    <link rel="stylesheet" href={% static 'css/mystyles.css' %}>
</head>

<body>

    <nav class="navbar is-danger" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <!-- <a class="navbar-item" href="https://bulma.io">
                <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
            </a> -->

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item">
                    Home
                </a>

                <a class="navbar-item">
                    Documentation
                </a>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        More
                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item">
                            About
                        </a>
                        <a class="navbar-item">
                            Jobs
                        </a>
                        <a class="navbar-item">
                            Contact
                        </a>
                        <hr class="navbar-divider" />
                        <a class="navbar-item">
                            Report an issue
                        </a>
                    </div>
                </div>
            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary">
                            <strong>Sign up</strong>
                        </a>
                        <a class="button is-link">
                            Log in
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </nav>


    <section class="section">
        <div class="container">


            <nav class="pagination is-rounded" role="navigation" aria-label="pagination">
                {% if page_obj.has_previous %}
                <a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                {% endif %}

                {% if page_obj.has_next %}
                <a class="pagination-next" href="?page={{ page_obj.next_page_number }}">Next page</a>
                {% endif %}



                <ul class="pagination-list">
                    {% for num in page_obj.paginator.page_range %}
                    <!-- Active page -->
                    {% comment %} {% if num == page_obj.number %}
                    <ul>
                        <a class="pagination-link is-current" href="?page={{ num }}">{{ num }}</a>
                    </ul>

                    {% else %} {% endcomment %}
                    <!-- For the 1st page we do not use ?page=1 -->
                    {% if num == 1 %}
                    <a class="pagination-link" href="?page={{ num }}">{{ num }}</a>

                    {% else %}
                    <!-- Show current page and +-3 pages -->
                    {% if num|add:"-3" <= page_obj.number and page_obj.number <= num|add:"3" %}
                    <a class="pagination-link" href="?page={{ num }}">{{ num }}</a>

                    <!-- Shows every 10th page and the last page -->
                    {% elif num|divisibleby:"10" or num == page_obj.paginator.num_pages %}
                    <a class="pagination-link" href="?page={{ num }}">{{ num }}</a>
                    {% endif %}

                    {% endif %}
                    {% comment %} {% endif %} {% endcomment %}

                    {% endfor %}
                </ul>



                {% comment %} <ul class="pagination-list">

                    {% if page_obj.has_previous %}
                    <li><a class="pagination-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
                    <li><span class="pagination-ellipsis">&hellip;</span></li>
                    {% endif %}


                    {% for num in page_obj.paginator.page_range %}
                    {% ifequal num page_obj.number %}
                    <li><a class="pagination-link is-current" aria-current="page">{{ num }}</a></li>
                    {% else %}
                    <li><a class="pagination-link " aria-current="page" href="?page={{ num }}">{{ num }}</a></li>
                    {% endifequal %}
                    {% endfor %} {% endcomment %}


                    {% comment %} {% if page_obj.has_next %} {% endcomment %}
                    {% comment %} <li><span class="pagination-ellipsis">&hellip;</span></li> {% endcomment %}
                    {% comment %} <li><a class="pagination-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
                    {% endif %}

                    <li><span class="pagination-ellipsis">&hellip;</span></li>
                    <li><a class="pagination-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li> {% endcomment %}
                    {% comment %}
                </ul> {% endcomment %}
            </nav>



            <div class="columns is-multiline">
                {% for product in products %}
                <div class="column is-2 is-4-mobile">
                    <div class="card">
                        <div class="card-image">
                            <figure class="image">
                                <img src="{{ product.image.url }}" alt="Placeholder image">
                            </figure>
                        </div>
                        <footer class="card-footer">
                            <a href="#" class="card-footer-item">{{ product.title }}</a>
                        </footer>

                    </div>
                </div>
                {% endfor %}

            </div>

    </section>

</body>

</html>

backend/main/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block nav %}
{% endblock nav %}

{% block content %}




<nav class="pagination is-rounded" role="navigation" aria-label="pagination">
    {% if page_obj.has_previous %}
    <a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% if page_obj.has_next %}
    <a class="pagination-next" href="?page={{ page_obj.next_page_number }}">Next page</a>
    {% endif %}

    <ul class="pagination-list">
        {% if page_obj.has_previous %}
        <li><a class="pagination-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
        <li><span class="pagination-ellipsis">&hellip;</span></li>
        {% endif %}

        <li><a class="pagination-link is-current" aria-current="page">{{ page_obj.number }}</a></li>

        {% if page_obj.has_next %}
        {% comment %} <li><span class="pagination-ellipsis">&hellip;</span></li> {% endcomment %}
        <li><a class="pagination-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
        {% endif %}

        <li><span class="pagination-ellipsis">&hellip;</span></li>
        <li><a class="pagination-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li>
    </ul>
</nav>


{% block product_list %}

{% endblock product_list %}



{% endblock content %}










<nav class="pagination is-rounded" role="navigation" aria-label="pagination">
    {% if page_obj.has_previous %}
    <a class="pagination-previous" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% if page_obj.has_next %}
    <a class="pagination-next" href="?page={{ page_obj.next_page_number }}">Next page</a>
    {% endif %}



    <ul class="pagination-list">
        {% if page_obj.has_previous %}
        <li><a class="pagination-link" href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
        <li><span class="pagination-ellipsis">&hellip;</span></li>
        {% endif %}


        {% for num in page_obj.paginator.page_range %}
        {% ifequal num page_obj.number %}
        <li><a class="pagination-link is-current" aria-current="page">{{ num }}</a></li>
        {% else %}
        <li><a class="pagination-link " aria-current="page" href="?page={{ num }}">{{ num }}</a></li>
        {% endifequal %}
        {% endfor %}


        {% comment %} {% if page_obj.has_next %} {% endcomment %}
        {% comment %} <li><span class="pagination-ellipsis">&hellip;</span></li> {% endcomment %}
        {% comment %} <li><a class="pagination-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
        {% endif %}

        <li><span class="pagination-ellipsis">&hellip;</span></li>
        <li><a class="pagination-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a></li> {% endcomment %}
    </ul>
</nav>

backend/main/templates/nav.html
{% extends 'base.html' %}
{% load static %}

{% block nav %}
<nav class="navbar is-danger" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <!-- <a class="navbar-item" href="https://bulma.io">
                <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
            </a> -->

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <a class="navbar-item">
                Home
            </a>

            <a class="navbar-item">
                Documentation
            </a>

            <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                    More
                </a>

                <div class="navbar-dropdown">
                    <a class="navbar-item">
                        About
                    </a>
                    <a class="navbar-item">
                        Jobs
                    </a>
                    <a class="navbar-item">
                        Contact
                    </a>
                    <hr class="navbar-divider" />
                    <a class="navbar-item">
                        Report an issue
                    </a>
                </div>
            </div>
        </div>

        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <a class="button is-primary">
                        <strong>Sign up</strong>
                    </a>
                    <a class="button is-link">
                        Log in
                    </a>
                </div>
            </div>
        </div>
    </div>
</nav>

{% endblock nav %}

backend/main/templates/product_list.html
{% extends 'base.html' %}
{% load static %}


{% block product_list %}
<section class="section">
    <div class="container">
        <div class="columns is-multiline">
            {% for product in products %}
            <div class="column is-2 is-4-mobile">
                <div class="card">
                    <div class="card-image">
                        <figure class="image">
                            <img src="{{ product.image.url }}" alt="Placeholder image">
                        </figure>
                    </div>
                    <footer class="card-footer">
                        <a href="#" class="card-footer-item">{{ product.title }}</a>
                    </footer>

                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock product_list %}